type PushNotificationSubscription {
    endpoint: String!
}

type Query {
    allPushNotificationSubscriptions: [PushNotificationSubscription]
    pushNotificationByEndpoint(endpoint: String): PushNotificationSubscription
}

type DeleteResponse {
    count: Int
}

type Mutation {
    deletePushNotificationByEndpoint(endpoint: String): DeleteResponse  @resolver(name: "delete_endpoint")
}