name: Create PR from Privacy Report Submission

on:
  issues:
    types: [opened]
  push:

jobs:
  createFile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: privacy-sub-form
          fetch-depth: 0
          persist-credentials: false
      - name: Create summary file
        env:
          FILE_CONTENT: ${{ github.event.issue.body }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          BRANCH_NAME: mytest
        run: |
          node content/privacy-reports/createPrivacySummaryFile.js
          ls content/privacy-reports
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -a
          git commit -m "Add New Privacy Summary File" --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          branch: $BRANCH_NAME