name: Create PR from Privacy Report Submission

on:
  issues:
    types: [opened]
  push:

jobs:
  createFile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: privacy-sub-form
          fetch-depth: 0
          persist-credentials: false
      - name: Create summary file
        env:
          FILE_CONTENT: ${{ github.event.issue.body }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          node content/privacy-reports/createPrivacySummaryFile.js
          ls content/privacy-reports

      