name: Create PR from Privacy Report Submission

on:
  issues:
    types: [opened]
  push:

jobs:
  createFile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: privacy-sub-form
          fetch-depth: 0
          persist-credentials: false
      - name: create_file
        env:
          FILE_CONTENT: ${{ github.event.issue.body }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          node content/privacy-reports/createPrivacySummaryFile.js
          ls content/privacy-reports
      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add New Privacy Summary File" --allow-empty
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          branch: issue${{ github.event.issue.number }}