name: Prettier for JS Code

on: [pull_request]

jobs:
  cleanup_tasks:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning the repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Prettify the JS Code
      uses: creyD/prettier_action@v2.0
      with:
        prettier_options: '--no-semi --write *.js'
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
